name: build-and-release-container

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: yaskkserv2
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +"%Y-%m-%d")"
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ steps.date.outputs.date }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=refistry,ref=latest
          cache-to: type=inline,mode=max
